# Generated by Django 4.1 on 2022-08-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsparser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(related_name='articles', to='newsparser.tag', verbose_name='Тэги'),
        ),
    ]
